/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestAPIServer;

import org.restlet.data.Protocol;
import RestAPIServer.controller.VmController;
import RestAPIServer.controller.VmRunActionController;
import RestAPIServer.controller.VmStopActionController;

import org.restlet.Application;
import org.restlet.Component;

public class App extends Application{
    public static void main(String[] args) throws Exception {

        System.out.println("REST API Server Start!");

        Component component =  new Component();
        component.getServers().add(Protocol.HTTP, 8888);

        component.getDefaultHost().attach("/vm/{macAddress}", VmController.class);
        component.getDefaultHost().attach("/vm", VmController.class);
        component.getDefaultHost().attach("/vm/action/run/{macAddress}", VmRunActionController.class);
        component.getDefaultHost().attach("/vm/action/stop/{macAddress}", VmStopActionController.class);

        component.start();
    }

}
